---
version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    # note that mongodb (from docs) writes its data on data/db folder
    volumes:
      - vidly:/data/db

volumes:
  vidly:

