---
version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  frontend-test:
    image: fullstack-compose_frontend
    volumes:
      - ./frontend:/app
    command: npm test

  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh
    # command: ./wait-for db:27017 && migrate mongo up && npm start

  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    # note that mongodb (from docs) writes its data on data/db folder
    volumes:
      - vidly:/data/db

volumes:
  vidly:

